version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - unused

formatters:
  exclusions:
    generated: lax

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
