name: Clean Up Untagged Manifests
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: picoaide/picoaide
          delete-only-untagged-versions: true
      - uses: actions/delete-package-versions@v5
        with:
          package-name: picoaide/picoaide-dev
          delete-only-untagged-versions: true
